services:
  - type: web
    name: king-deobfuscator
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: COMMAND_PREFIX
        value: "!"
